countries = ["France","Brazil","Afghanistan","Zimbabwe","China"]
print(countries)
countries.sort()
print(countries)
countries.sort(reverse=True)
print(countries)
countries.reverse()
print(countries)
countries.reverse()
print(countries)
countries.sort()
print(countries)
countries.sort(reverse=True)
print(countries)